-- CreateTable
CREATE TABLE `department` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `departmentCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `catagory` VARCHAR(191) NOT NULL DEFAULT 'Arts',

    UNIQUE INDEX `department_departmentCode_key`(`departmentCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `code` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `depCode` VARCHAR(191) NOT NULL,
    `uname` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staff` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uname` VARCHAR(191) NOT NULL,
    `staffName` VARCHAR(191) NOT NULL,
    `staffInitial` VARCHAR(191) NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `student` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `regNo` VARCHAR(191) NOT NULL,
    `claass` VARCHAR(191) NOT NULL,
    `section` VARCHAR(191) NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `marks` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `C1LOT` DOUBLE NULL,
    `C1MOT` DOUBLE NULL,
    `C1HOT` DOUBLE NULL,
    `C2LOT` DOUBLE NULL,
    `C2MOT` DOUBLE NULL,
    `C2HOT` DOUBLE NULL,
    `ASG1` DOUBLE NULL,
    `ASG2` DOUBLE NULL,
    `ASGCO1` DOUBLE NULL,
    `ASGCO2` DOUBLE NULL,
    `ELOT` DOUBLE NULL,
    `EMOT` DOUBLE NULL,
    `EHOT` DOUBLE NULL,
    `TLOT` DOUBLE NULL,
    `TMOT` DOUBLE NULL,
    `THOT` DOUBLE NULL,
    `C1STATUS` VARCHAR(191) NULL,
    `C2STATUS` VARCHAR(191) NULL,
    `ESTATUS` VARCHAR(191) NULL,
    `C1STAFF` VARCHAR(191) NULL,
    `C2STAFF` VARCHAR(191) NULL,
    `ESTAFF` VARCHAR(191) NULL,
    `ASG1STAFF` VARCHAR(191) NULL,
    `ASG2STAFF` VARCHAR(191) NULL,
    `studentId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PSO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PSO1CO1` INTEGER NOT NULL,
    `PSO1CO2` INTEGER NOT NULL,
    `PSO1CO3` INTEGER NOT NULL,
    `PSO1CO4` INTEGER NOT NULL,
    `PSO1CO5` INTEGER NOT NULL,
    `PSO2CO1` INTEGER NOT NULL,
    `PSO2CO2` INTEGER NOT NULL,
    `PSO2CO3` INTEGER NOT NULL,
    `PSO2CO4` INTEGER NOT NULL,
    `PSO2CO5` INTEGER NOT NULL,
    `PSO3CO1` INTEGER NOT NULL,
    `PSO3CO2` INTEGER NOT NULL,
    `PSO3CO3` INTEGER NOT NULL,
    `PSO3CO4` INTEGER NOT NULL,
    `PSO3CO5` INTEGER NOT NULL,
    `PSO4CO1` INTEGER NOT NULL,
    `PSO4CO2` INTEGER NOT NULL,
    `PSO4CO3` INTEGER NOT NULL,
    `PSO4CO4` INTEGER NOT NULL,
    `PSO4CO5` INTEGER NOT NULL,
    `PSO5CO1` INTEGER NOT NULL,
    `PSO5CO2` INTEGER NOT NULL,
    `PSO5CO3` INTEGER NOT NULL,
    `PSO5CO4` INTEGER NOT NULL,
    `PSO5CO5` INTEGER NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` ENUM('Admin', 'Staff') NOT NULL DEFAULT 'Staff',
    `name` VARCHAR(191) NOT NULL DEFAULT 'none',
    `uname` VARCHAR(191) NOT NULL DEFAULT 'Staffid',

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `code` ADD CONSTRAINT `code_depCode_fkey` FOREIGN KEY (`depCode`) REFERENCES `department`(`departmentCode`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `staff` ADD CONSTRAINT `staff_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `student` ADD CONSTRAINT `student_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `marks` ADD CONSTRAINT `marks_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PSO` ADD CONSTRAINT `PSO_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
