-- CreateTable
CREATE TABLE `department` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `departmentCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `department_departmentCode_key`(`departmentCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `code` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `depCode` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `student` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `regNo` VARCHAR(191) NOT NULL,
    `class` VARCHAR(191) NOT NULL,
    `section` VARCHAR(191) NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `marks` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `C1Q1` DOUBLE NOT NULL,
    `C1Q2` DOUBLE NOT NULL,
    `C1Q3` DOUBLE NOT NULL,
    `C1Q4` DOUBLE NOT NULL,
    `C1Q5` DOUBLE NOT NULL,
    `C1Q6` DOUBLE NOT NULL,
    `C1Q7` DOUBLE NOT NULL,
    `C1Q8` DOUBLE NOT NULL,
    `C1Q9` DOUBLE NOT NULL,
    `C1Q10` DOUBLE NOT NULL,
    `C1Q11` DOUBLE NOT NULL,
    `C1Q12` DOUBLE NOT NULL,
    `C1Q13` DOUBLE NOT NULL,
    `C1Q14` DOUBLE NOT NULL,
    `C1Q15` DOUBLE NOT NULL,
    `C1Q16` DOUBLE NOT NULL,
    `C1Q17` DOUBLE NOT NULL,
    `C1Q18` DOUBLE NOT NULL,
    `C1Q19` DOUBLE NOT NULL,
    `C1Q20` DOUBLE NOT NULL,
    `C1Q21` DOUBLE NOT NULL,
    `C1Q22` DOUBLE NOT NULL,
    `C1Q23` DOUBLE NOT NULL,
    `C1Q24` DOUBLE NOT NULL,
    `C1Q25` DOUBLE NOT NULL,
    `C1Q26` DOUBLE NOT NULL,
    `C1Q27` DOUBLE NOT NULL,
    `C1Q28` DOUBLE NOT NULL,
    `C2Q1` DOUBLE NOT NULL,
    `C2Q2` DOUBLE NOT NULL,
    `C2Q3` DOUBLE NOT NULL,
    `C2Q4` DOUBLE NOT NULL,
    `C2Q5` DOUBLE NOT NULL,
    `C2Q6` DOUBLE NOT NULL,
    `C2Q7` DOUBLE NOT NULL,
    `C2Q8` DOUBLE NOT NULL,
    `C2Q9` DOUBLE NOT NULL,
    `C2Q10` DOUBLE NOT NULL,
    `C2Q11` DOUBLE NOT NULL,
    `C2Q12` DOUBLE NOT NULL,
    `C2Q13` DOUBLE NOT NULL,
    `C2Q14` DOUBLE NOT NULL,
    `C2Q15` DOUBLE NOT NULL,
    `C2Q16` DOUBLE NOT NULL,
    `C2Q17` DOUBLE NOT NULL,
    `C2Q18` DOUBLE NOT NULL,
    `C2Q19` DOUBLE NOT NULL,
    `C2Q20` DOUBLE NOT NULL,
    `C2Q21` DOUBLE NOT NULL,
    `C2Q22` DOUBLE NOT NULL,
    `C2Q23` DOUBLE NOT NULL,
    `C2Q24` DOUBLE NOT NULL,
    `C2Q25` DOUBLE NOT NULL,
    `C2Q26` DOUBLE NOT NULL,
    `C2Q27` DOUBLE NOT NULL,
    `C2Q28` DOUBLE NOT NULL,
    `ESEQ1` DOUBLE NOT NULL,
    `ESEQ2` DOUBLE NOT NULL,
    `ESEQ3` DOUBLE NOT NULL,
    `ESEQ4` DOUBLE NOT NULL,
    `ESEQ5` DOUBLE NOT NULL,
    `ESEQ6` DOUBLE NOT NULL,
    `ESEQ7` DOUBLE NOT NULL,
    `ESEQ8` DOUBLE NOT NULL,
    `ESEQ9` DOUBLE NOT NULL,
    `ESEQ10` DOUBLE NOT NULL,
    `ESEQ11` DOUBLE NOT NULL,
    `ESEQ12` DOUBLE NOT NULL,
    `ESEQ13` DOUBLE NOT NULL,
    `ESEQ14` DOUBLE NOT NULL,
    `ESEQ15` DOUBLE NOT NULL,
    `ESEQ16` DOUBLE NOT NULL,
    `ESEQ17` DOUBLE NOT NULL,
    `ESEQ18` DOUBLE NOT NULL,
    `ESEQ19` DOUBLE NOT NULL,
    `ESEQ20` DOUBLE NOT NULL,
    `ESEQ21` DOUBLE NOT NULL,
    `ESEQ22` DOUBLE NOT NULL,
    `ESEQ23` DOUBLE NOT NULL,
    `ESEQ24` DOUBLE NOT NULL,
    `ESEQ25` DOUBLE NOT NULL,
    `ESEQ26` DOUBLE NOT NULL,
    `ESEQ27` DOUBLE NOT NULL,
    `ESEQ28` DOUBLE NOT NULL,
    `ASG1` DOUBLE NOT NULL,
    `ASG2` DOUBLE NOT NULL,
    `ASGCO1` DOUBLE NOT NULL,
    `ASGCO2` DOUBLE NOT NULL,
    `ASGCO3` DOUBLE NOT NULL,
    `ASGCO4` DOUBLE NOT NULL,
    `ASGCO5` DOUBLE NOT NULL,
    `C1CO1` DOUBLE NOT NULL,
    `C1CO2` DOUBLE NOT NULL,
    `C1CO3` DOUBLE NOT NULL,
    `C1CO4` DOUBLE NOT NULL,
    `C1CO5` DOUBLE NOT NULL,
    `C2CO1` DOUBLE NOT NULL,
    `C2CO2` DOUBLE NOT NULL,
    `C2CO3` DOUBLE NOT NULL,
    `C2CO4` DOUBLE NOT NULL,
    `C2CO5` DOUBLE NOT NULL,
    `ESECO1` DOUBLE NOT NULL,
    `ESECO2` DOUBLE NOT NULL,
    `ESECO3` DOUBLE NOT NULL,
    `ESECO4` DOUBLE NOT NULL,
    `ESECO5` DOUBLE NOT NULL,
    `TCO1` DOUBLE NOT NULL,
    `TCO2` DOUBLE NOT NULL,
    `TCO3` DOUBLE NOT NULL,
    `TCO4` DOUBLE NOT NULL,
    `TCO5` DOUBLE NOT NULL,
    `C1STATUS` VARCHAR(191) NOT NULL,
    `C2STATUS` VARCHAR(191) NOT NULL,
    `ESESTATUS` VARCHAR(191) NOT NULL,
    `STAFF` VARCHAR(191) NOT NULL,
    `studentId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `code` ADD CONSTRAINT `code_depCode_fkey` FOREIGN KEY (`depCode`) REFERENCES `department`(`departmentCode`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `student` ADD CONSTRAINT `student_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `marks` ADD CONSTRAINT `marks_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
