-- CreateTable
CREATE TABLE `PSO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PSO1CO1` INTEGER NOT NULL,
    `PSO1CO2` INTEGER NOT NULL,
    `PSO1CO3` INTEGER NOT NULL,
    `PSO1CO4` INTEGER NOT NULL,
    `PSO1CO5` INTEGER NOT NULL,
    `PSO2CO1` INTEGER NOT NULL,
    `PSO2CO2` INTEGER NOT NULL,
    `PSO2CO3` INTEGER NOT NULL,
    `PSO2CO4` INTEGER NOT NULL,
    `PSO2CO5` INTEGER NOT NULL,
    `PSO3CO1` INTEGER NOT NULL,
    `PSO3CO2` INTEGER NOT NULL,
    `PSO3CO3` INTEGER NOT NULL,
    `PSO3CO4` INTEGER NOT NULL,
    `PSO3CO5` INTEGER NOT NULL,
    `PSO4CO1` INTEGER NOT NULL,
    `PSO4CO2` INTEGER NOT NULL,
    `PSO4CO3` INTEGER NOT NULL,
    `PSO4CO4` INTEGER NOT NULL,
    `PSO4CO5` INTEGER NOT NULL,
    `PSO5CO1` INTEGER NOT NULL,
    `PSO5CO2` INTEGER NOT NULL,
    `PSO5CO3` INTEGER NOT NULL,
    `PSO5CO4` INTEGER NOT NULL,
    `PSO5CO5` INTEGER NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PSO` ADD CONSTRAINT `PSO_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
